---
title: "Load and Clean Studbook Data for Pygmy Slow Loris Provisional SSP"
author: "Alicia Rich"
output: learnr::tutorial
    code_folding: "show"
runtime: shiny_prerendered

---

```{r}
library(knitr)
library(bibtex)
library(bookdown)
library(bsicons)
library(bslib)
library(conflicted)
library(devtools)
library(downloadthis)
library(fontawesome)
library(glue)
library(heatmaply)
library(here)
library(htmltools)
library(htmlwidgets)
library(kableExtra)
library(kinship2)
library(paletteer)
library(pedsuite)
library(plotly)
library(reactable)
library(reactablefmtr)
library(rmarkdown)
library(scales)
library(shiny)
library(showtext)
library(thematic)
library(tidyverse)
library(tippy)
library(tsibble)
library(usethis)
library(visNetwork)
library(rmdformats)
library(zoolabs)
```

```{r}
conflicts_prefer(lubridate::interval)
```

```{r message=FALSE, warning=FALSE}
loc_key   <- read_locations("../extdata/locations.csv", "../extdata/locations_clean.csv", "stratigraphy")
btp       <- read_btp("../extdata/btp.csv", "../extdata/btp_clean.csv", loc_key)
studbook  <- read_studbook("../extdata/studbook.csv", loc_key, btp)
```

```{r message=FALSE, warning=FALSE}
missing_dads <- find_parent(studbook, loc_key, "sire")
missing_moms <- find_parent(studbook, loc_key, "dam")
hyp_defs <- list(
  sires = list(
    c(1045, 1046),
    2108,
    1087,
    2717
    ),
  dams = list(
    1087,
    2717
    )
  )

```

```{r}
studbook_revised <- studbook %>%
  mutate(
    Sire = case_match(ID, 
                      1047 ~ 1012, 
                      2738 ~ 2622, 
                      .default = Sire),
    Dam  = case_match(ID, 
                      2738 ~ 2630, 
                      .default = Dam)
  ) %>%
  add_all_hypotheticals(hyp_defs, loc_key)
write_csv(studbook_revised, "../extdata/studbook_revised.csv")
```

