---
title: "Code Scratch"
author: "Alicia Rich"
date: "`r Sys.Date()`"
output: html_document
                     
---

```{r}
library(tidyverse)
library(htmlwidgets)
library(htmltools)
library(conflicted)
conflicts_prefer(lubridate::interval)
conflicts_prefer(dplyr::filter)
conflicts_prefer(purrr::set_names)
studbook <- read_csv("../inst/extdata/studbook.csv")

knitr::opts_chunk$set(
  collapse = TRUE,
  message  = FALSE,
  warning  = FALSE,
  echo     = FALSE,
  include  = TRUE,
  eval     = TRUE,
  comment  = ""
)
```

```{r}
first_cap <- filter(studbook, Type_birth == "Captive") %>% pull(Date_birth) %>% min()
```


```{r}
window <- c(first_cap, max(studbook$Date_birth))
```


```{r}
lt_deaths <- lt_studbook %>%
  filter(Status == "D") %>%
  select(
    ID,
    Sex,
    Qtr_birth,
    Qtr_death = Qtr_last,
    Type_birth
  ) %>%
  distinct() %>%
  mutate(x_death = ceiling(time_length(interval(Qtr_birth, Qtr_death), "year")))
```

```{r}
lt_studbook <- studbook %>%
  filter(between(Date_birth, window[1], window[2]) & Status %in% c("A", "D")) %>%
  select(ID, 
         Date_birth, 
         Date, 
         Event, 
         Date_last, 
         Status, 
         Sex, 
         Sire, 
         Dam,
         Type_birth) %>%
  mutate(Qtr_born = quarter(Date_birth, type = "date_first"),
         Qtr_last  = quarter(Date_last, type = "date_first"))
```

```{r}
age_classes <- studbook %>%
    filter(between(Date_birth, window[1], window[2]) & Status %in% c("A", "D")) %>%
    mutate(Month_born  = floor_date(Date_birth, "month"),
           Month_last  = ceiling_date(Date_last, "month")) %>%
    mutate(x_last = ceiling(time_length(interval(Month_born, Month_last), "year"))) %>%
    distinct(
      ID,
      Sex,
      Type_birth,
      Status,
      Month_born,
      x_last
      ) %>%
    mutate(x = pmap(list(0, x_last), \(x, y) seq(x, y, by = 1))) %>%
    unnest(x) %>%
    rowwise() %>%
    mutate(x_start = Month_born + years(x)) %>%
    mutate(x_end   = x_start + years(1) - days(1)) %>%
    ungroup() %>%
    select(
      ID,
      Sex,
      Type_birth,
      Status,
      Month_born,
      x,
      x_start,
      x_end
    ) %>%
    arrange(ID, x_start, x)
```

```{r}
births <- studbook %>%
    filter(between(Date_birth, window[1], window[2]) & Status %in% c("A", "D")) %>%
    mutate(Month_birth  = floor_date(Date_birth, "month")) %>%
    select(
      ID_birth  = ID,
      sex_birth = Sex,
      Month_birth,
      Sire,
      Dam
      ) %>%
  distinct() %>%
  pivot_longer(c(Sire, Dam), names_to = "parent", values_to = "ID") %>%
  filter(ID != 0) %>%
  select(ID, ID_birth, sex_birth, Month_birth)
```

```{r}
fecund <- distinct(age_classes,
                   ID,
                   Month_born) %>%
  left_join(births, by = "ID") %>%
  rowwise() %>%
  mutate(x = floor(time_length(interval(Month_born, Month_birth), "year"))) %>%
  distinct(
    ID,
    ID_birth,
    sex_birth,
    x
  ) %>%
  filter(!is.na(ID_birth)) %>%
  left_join(age_classes, by = join_by(ID, x)) %>%
  select(
    ID,
    Sex,
    Status,
    Type_birth,
    Month_born,
    x,
    ID_birth,
    sex_birth,
    x_start,
    x_end
  ) %>%
  arrange(ID, x, ID_birth)
```

```{r}
age_classes_qtr <- studbook %>%
    filter(between(Date_birth, window[1], window[2]) & Status %in% c("A", "D")) %>%
    mutate(Qtr_born  = quarter(Date_birth, type = "date_first"),
           Qtr_last  = quarter(Date_last, type = "date_last")) %>%
    mutate(x_last = ceiling(time_length(interval(Qtr_born, Qtr_last), "year"))) %>%
    distinct(
      ID,
      Sex,
      Type_birth,
      Status,
      Qtr_born,
      x_last
      ) %>%
    mutate(x = pmap(list(0, x_last), \(x, y) seq(x, y, by = 1))) %>%
    unnest(x) %>%
    rowwise() %>%
    mutate(x_start = Qtr_born + years(x)) %>%
    mutate(x_end   = x_start + years(1) - days(1)) %>%
    ungroup() %>%
    select(
      ID,
      Sex,
      Type_birth,
      Status,
      Qtr_born,
      x,
      x_start,
      x_end
    ) %>%
    arrange(ID, x_start, x)
```

```{r}
births_qtr <- studbook %>%
    filter(between(Date_birth, window[1], window[2]) & Status %in% c("A", "D")) %>%
    mutate(Qtr_birth  = quarter(Date_birth, type = "date_first")) %>%
    select(
      ID_birth  = ID,
      sex_birth = Sex,
      Qtr_birth,
      Sire,
      Dam
      ) %>%
  distinct() %>%
  pivot_longer(c(Sire, Dam), names_to = "parent", values_to = "ID") %>%
  filter(ID != 0) %>%
  select(ID, ID_birth, sex_birth, Qtr_birth)
```

```{r}
fecund_qtr <- distinct(age_classes_qtr,
                   ID,
                   Qtr_born) %>%
  left_join(births_qtr, by = "ID") %>%
  rowwise() %>%
  mutate(x = floor(time_length(interval(Qtr_born, Qtr_birth), "year"))) %>%
  distinct(
    ID,
    ID_birth,
    sex_birth,
    x
  ) %>%
  filter(!is.na(ID_birth)) %>%
  left_join(age_classes_qtr, by = join_by(ID, x)) %>%
  select(
    ID,
    Sex,
    Status,
    Type_birth,
    Qtr_born,
    x,
    ID_birth,
    sex_birth,
    x_start,
    x_end
  ) %>%
  arrange(ID, x, ID_birth)
```

```{r}
ggplot(fecund_qtr, aes(x)) +
  geom_histogram()
ggplot(fecund, aes(x)) +
  geom_histogram()
```



```{r setup, include=FALSE}
library(devtools)
library(roxygen2)
```

```{r include=FALSE}
document()
```


```{r include=FALSE}
install()
```

```{r}
library(zoopop)
```

```{r}
ages <- age_classes_ids(studbook) %>%
  distinct(Sex, x)

mortality <- mortality_history(studbook) %>%
  group_by(Sex, x_death) %>%
  reframe(deaths = n()) %>%
  ungroup() %>%
  rename(x = x_death) %>%
  right_join(ages, by = join_by(Sex, x)) %>%
  mutate(deaths    = replace_na(deaths, 0)) %>%
  arrange(x, Sex) %>%
  pivot_wider(names_from   = "Sex",
              names_prefix = "deaths_",
              values_from  = "deaths",
              values_fill  = 0) %>%
  rowwise() %>%
  mutate(deaths_T = sum(across(starts_with("deaths")))) %>%
  ungroup()

repro <- repro_history(studbook) %>%
  group_by(Sex, x) %>%
  reframe(births = n()) %>%
  ungroup() %>%
  right_join(ages, by = join_by(Sex, x)) %>%
  mutate(births    = replace_na(births, 0)) %>%
  arrange(x, Sex) %>%
  pivot_wider(names_from   = "Sex",
              names_prefix = "births_",
              values_from  = "births",
              values_fill  = 0)%>%
  rowwise() %>%
  mutate(births_T = sum(across(starts_with("births")))) %>%
  ungroup()
```

```{r}
ages <- age_classes_ids(studbook) %>%
  distinct(Sex, x)

mortality <- mortality_history(studbook) %>%
  group_by(Sex, x_death) %>%
  reframe(deaths = n()) %>%
  ungroup() %>%
  rename(x = x_death) %>%
  right_join(ages, by = join_by(Sex, x)) %>%
  mutate(deaths    = replace_na(deaths, 0)) %>%
  arrange(x, Sex) %>%
  mutate(Total = sum(deaths), .by = "x") %>%
  pivot_longer("Total", names_to = "Sex", values_to = "deaths")

repro <- repro_history(studbook) %>%
  group_by(Sex, x) %>%
  reframe(births = n()) %>%
  ungroup() %>%
  right_join(ages, by = join_by(Sex, x)) %>%
  mutate(births    = replace_na(births, 0)) %>%
  arrange(x, Sex) %>%
  pivot_wider(names_from   = "Sex",
              names_prefix = "births_",
              values_from  = "births",
              values_fill  = 0)%>%
  rowwise() %>%
  mutate(births_T = sum(across(starts_with("births")))) %>%
  ungroup()
```


```{r}
count_tbl <- age_classes_ids(studbook) %>%
  summarize(risk = n(), .by = c(Sex, x)) %>%
  pivot_wider(names_from   = "Sex", 
              names_prefix = "risk_",
              values_from  = "risk", 
              values_fill  = 0) %>%
  rowwise() %>%
  mutate(risk_T = sum(across(starts_with("risk")))) %>%
  ungroup() %>%
  left_join(repro, by = "x") %>%
  left_join(mortality, by = "x") %>%
  select(
    x,
    risk_M,
    births_M,
    deaths_M,
    risk_F,
    births_F,
    deaths_F,
    risk_T,
    births_T,
    deaths_T
  )
```

```{r}
lt_raw <- count_tbl %>%
  pivot_longer(c(starts_with(c("births", "deaths"))),
               names_to = "Sex",
               values_to)
  
```




