---
title: "development"
output: html_document
---

x	x+n	deaths	pop	mx	ax	qx	px	lx	dx	nLx	Tx	ex

```{r warning=FALSE}
library(tidyverse)
studbook <- read_csv("../inst/extdata/studbook.csv")
```


```{r}
studbook_dates <- studbook %>%
    filter(Sex != "U") %>%
    distinct(
      ID,
      Date_birth,
      Date_last,
      Sex
    ) %>%
    mutate(born = year(Date_birth),
           end  = year(Date_last), .keep = "unused") %>%
    mutate(age_end = as.integer(end) - as.integer(born))

span     <- 5
age_max  <- max(studbook_dates$age_end)
year_min <- min(studbook_dates$born)
year_max <- (year(today()) + 1)
year     <- seq(year_min, year(today()), by = 1)
start    <- seq(year_min, (year_max - 1), by = span)
end      <- start + (span - 1)
sex      <- unique(pull(studbook_dates, Sex))
x        <- c(0:age_max)
```

```{r}
cohorts <- tibble(start, end) %>%
  mutate(cohort = row_number()) %>%
  mutate(born = pmap(list(start, end), \(x, y) seq(x, y, by = 1))) %>%
  unnest(born) %>%
  select(cohort,
         cohort_start = start,
         cohort_end   = end,
         born) %>%
  expand_grid(sex) %>%
  expand_grid(x) %>%
  rowwise() %>%
  mutate(x_n = x + 1) %>%
  ungroup() %>%
  filter(born <= year(today()) & (born + x) <= year(today())) %>%
  arrange(cohort, cohort_start, born, sex, x) %>%
  mutate(year = born + x) %>%
  select(
    cohort,
    cohort_start,
    born,
    cohort_end,
    sex,
    year,
    x,
    x_n
  )
```

```{r}
  studbook_dates <- studbook %>%
    filter(Sex != "U") %>%
    distinct(
      ID,
      Date_birth,
      Date_last,
      Sex
    ) %>%
    mutate(born = year(Date_birth),
           end  = year(Date_last), .keep = "unused") %>%
    select(ID, sex = Sex, born, end)

```

```{r}
cohort_studbook <- cohorts %>%
    right_join(studbook_dates, by = join_by(born, sex)) %>%
    filter(year <= end) %>%
    arrange(cohort, cohort_start, born, year, x) %>%
    select(
      cohort,
      cohort_start,
      born,
      cohort_end,
      ID,
      sex,
      year,
      x,
      x_n
    )
```


```{r}
studbook_births <- studbook  %>%
    distinct(
      ID,
      Date_birth,
      Sire,
      Dam
    ) %>%
    mutate(year     = year(Date_birth), 
           birth_id = ID,
           .keep = "unused") %>%
  pivot_longer(
    c(Sire, Dam),
    names_to  = "sex",
    values_to = "ID"
  ) %>%
  filter(ID != 0) %>%
  mutate(sex = case_match(sex, "Dam" ~ "F", "Sire" ~ "M")) %>%
  distinct() %>%
  group_by(year, sex, ID) %>%
  reframe(births = n()) %>%
  ungroup() %>%
  right_join(cohort_studbook, by = join_by(sex, ID, year)) %>%
  arrange(cohort, cohort_start, born, year, x) %>%
  select(
    cohort,
    cohort_start,
    born,
    cohort_end,
    ID,
    sex,
    year,
    x,
    x_n,
    births
  ) %>%
  mutate(births = replace_na(births, 0))
```

```{r}
  studbook_dates <- studbook %>%
    filter(Sex != "U") %>%
    distinct(
      ID,
      Date_birth,
      Date_last,
      Sex
    ) %>%
    mutate(born = year(Date_birth),
           end  = year(Date_last), .keep = "unused")

```



```{r}
census <- cohorts %>%
  distinct(
    cohort,
    cohort_start,
    cohort_end,
    born,
    sex
  ) %>%
  right_join(studbook_dates, by = join_by(born, sex == Sex)) %>%
  mutate(year = pmap(list(born, end), \(x, y) seq(x, y, by = 1))) %>%
  unnest(year) %>%
  mutate(x = year - born) %>%
  group_by(born,
           sex,
           year,
           x) %>%
  reframe(pop = n()) %>%
  right_join(cohorts, by = join_by(sex, x, born)) %>%
  arrange(born, year, x, sex) %>%
  rowwise() %>%
  mutate(year = replace_na(year, born + x),
         pop  = replace_na(pop, 0)) %>%
  ungroup() %>%
  mutate(deaths = if_else(x < max(x), 
                          pop - lead(pop), 
                          pop), 
         .by = c(born, sex)) %>%
  pivot_wider(
    names_from   = "sex",
    names_sep    = "_",
    values_from  = c("pop", "deaths")
  ) %>%
  rowwise() %>%
  mutate(pop    = sum(pop_M, pop_F),
         deaths = sum(deaths_M, deaths_F)) %>%
  select(
    cohort,
    cohort_start,
    born,
    cohort_end,
    x,
    x_n,
    year,
    pop_M,
    deaths_M,
    pop_F,
    deaths_F,
    pop,
    deaths
  )
```

```{r}
census_cohorts_age <- census %>%
  group_by(cohort, 
           cohort_start, 
           cohort_end, 
           x,
           x_n) %>%
  summarize(pop_M    = sum(pop_M),
            deaths_M = sum(deaths_M),
            pop_F    = sum(pop_F),
            deaths_F = sum(deaths_F),
            pop      = sum(pop),
            deaths   = sum(deaths))
```


```{r}
census_annual_overall <- census %>%
  group_by(cohort, 
           cohort_start, 
           cohort_end,
           year) %>%
  summarize(pop_M    = sum(pop_M),
            deaths_M = sum(deaths_M),
            pop_F    = sum(pop_F),
            deaths_F = sum(deaths_F),
            pop      = sum(pop),
            deaths   = sum(deaths))
```


