# variables.R
# Declares all non-standard evaluation variables used across the package

utils::globalVariables(c(
  ".",
  "Age",
  "BTP",
  "Birth_Type",
  "Breeding Country",
  "Country_birth",
  "Dam Date",
  "Date_birth",
  "Date_event",
  "Date_last Dates",
  "Disposition",
  "End",
  "Event",
  "Facility_Note",
  "ID",
  "Individuals",
  "Institution",
  "Institution_birth",
  "Loc_birth",
  "Loc_end",
  "Loc_event",
  "Loc_last",
  "Loc_start",
  "Location",
  "Location_current",
  "Location_transfer",
  "Mnemonic",
  "Notes",
  "Sex",
  "Sire",
  "Start",
  "State_Province",
  "State_Province_birth",
  "Status",
  "Type_birth",
  "With",
  "Year_birth",
  "age",
  "birth",
  "capture",
  "code",
  "code1",
  "code2",
  "code_country",
  "colorLoc",
  "colorLoc_birth",
  "death",
  "event_order",
  "exclude",
  "facility",
  "iconLoc",
  "iconLoc_birth",
  "include",
  "loc_order",
  "mate",
  "note",
  "palettes_d",
  "transfer",
  "ungroup",
  "Breeding",
  "Country",
  "Dam",
  "Date",
  "Date_last",
  "Dates"
))


